"use client";
import "./globals.css";
import type { Metadata } from "next";
import Nav from "./components/nav/Nav";

export const metadata: Metadata = {
    title: "Addison Adult League Portal",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <Nav />
                {children}
            </body>
        </html>
    );
}
